import { useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { Eye, EyeOff, Briefcase, Megaphone, ShieldCheck } from "lucide-react";
import { useLogin } from "../../../hooks/useLogin";
import FacebookIcon from "../../../assets/Facebook.png";
import GoogleIcon from "../../../assets/google.webp";
import TiktokIcon from "../../../assets/tiktok.jpeg";

export default function LoginForm() {
    const {
        emailAddress,
        setEmailAddress,
        password,
        setPassword,
        error,
        loading,
        role,
        setRole,
        onSignInPress,
        handleSocialAuth,
        status,
        verificationCode,
        setVerificationCode,
        onVerifySecondFactor,
    } = useLogin();

    const [showPassword, setShowPassword] = useState(false);

    const handleSubmit = async (e: FormEvent) => {
        e.preventDefault();
        if (status === "needs_second_factor") {
            await onVerifySecondFactor();
        } else {
            await onSignInPress();
        }
    };

    return (
        <div className="flex flex-col">
            <div className="mb-10 text-left">
                <h2 className="text-4xl font-bold text-[#001e00] mb-3">Welcome back</h2>
                <p className="text-base text-[#5e6d55]">
                    Enter your credentials to access your account.
                </p>
            </div>

            <form onSubmit={handleSubmit} className="space-y-6">
                {error && (
                    <div className="p-3 bg-red-50 border border-red-100 text-red-600 text-sm rounded-xl text-center font-medium">
                        {error}
                    </div>
                )}

                {status === "needs_second_factor" ? (
                    <div>
                        <label className="mb-1.5 block text-sm font-bold text-[#001e00]">
                            Verification Code
                        </label>
                        <input
                            type="text"
                            value={verificationCode}
                            onChange={(e) => setVerificationCode(e.target.value)}
                            placeholder="Enter 6-digit code"
                            className="w-full rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm text-[#001e00] placeholder-gray-400 transition-all focus:border-[#14a800] focus:ring-1 focus:ring-[#14a800] outline-none"
                            required
                        />
                        <p className="mt-2 text-xs text-gray-500">
                            Please enter the code sent to your email or generated by your authenticator app.
                        </p>
                    </div>
                ) : (
                    <>
                        <div>
                            <label className="mb-1.5 block text-sm font-bold text-[#001e00]">
                                Email Address
                            </label>
                            <input
                                type="email"
                                value={emailAddress}
                                onChange={(e) => setEmailAddress(e.target.value)}
                                placeholder="you@example.com"
                                className="w-full rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm text-[#001e00] placeholder-gray-400 transition-all focus:border-[#14a800] focus:ring-1 focus:ring-[#14a800] outline-none"
                                required
                            />
                        </div>

                        <div>
                            <label className="mb-1.5 block text-sm font-bold text-[#001e00]">
                                Password
                            </label>
                            <div className="relative">
                                <input
                                    type={showPassword ? "text" : "password"}
                                    value={password}
                                    onChange={(e) => setPassword(e.target.value)}
                                    placeholder="Enter your password"
                                    className="w-full rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm text-[#001e00] placeholder-gray-400 transition-all focus:border-[#14a800] focus:ring-1 focus:ring-[#14a800] outline-none"
                                    required
                                />
                                <button
                                    type="button"
                                    onClick={() => setShowPassword(!showPassword)}
                                    className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-[#14a800] transition-colors"
                                >
                                    {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                                </button>
                            </div>
                        </div>

                        <div className="flex items-center justify-between">
                            <label className="flex items-center gap-2 cursor-pointer group">
                                <input
                                    type="checkbox"
                                    className="h-4 w-4 rounded border-gray-300 bg-white text-[#14a800] focus:ring-[#14a800] accent-[#14a800]"
                                />
                                <span className="text-sm font-medium text-[#5e6d55] group-hover:text-[#001e00] transition-colors">
                                    Keep me signed in
                                </span>
                            </label>
                            <Link
                                to="/auth/forgot-password"
                                className="text-sm font-bold text-[#14a800] hover:underline"
                            >
                                Forgot password?
                            </Link>
                        </div>
                    </>
                )}

                <button
                    type="submit"
                    disabled={loading}
                    className="w-full rounded-full bg-[#14a800] py-3.5 text-base font-bold text-white shadow-sm shadow-[#14a800]/20 transition-all hover:bg-[#108a00] active:scale-[0.98] disabled:opacity-50 flex items-center justify-center gap-2"
                >
                    {loading ? "Processing..." : status === "needs_second_factor" ? "Verify Code" : "Log In"}
                </button>
            </form>

            <div className="space-y-4 mt-8">
                <label className="text-xs font-bold text-[#5e6d55] uppercase tracking-wider block text-center">
                    Select your role for social login
                </label>
                <div className="grid grid-cols-3 gap-3">
                    <button
                        type="button"
                        onClick={() => setRole('business_owner')}
                        className={`flex flex-col items-center gap-2 p-4 rounded-xl border-2 transition-all ${role === 'business_owner'
                            ? 'border-[#14a800] bg-[#14a800]/5 text-[#14a800]'
                            : 'border-gray-100 bg-white text-[#5e6d55] hover:border-[#14a800]/30 hover:text-[#001e00]'
                            }`}
                    >
                        <Briefcase size={20} />
                        <span className="text-[10px] font-black uppercase tracking-tight">Business</span>
                    </button>
                    <button
                        type="button"
                        onClick={() => setRole('advertiser')}
                        className={`flex flex-col items-center gap-2 p-4 rounded-xl border-2 transition-all ${role === 'advertiser'
                            ? 'border-[#14a800] bg-[#14a800]/5 text-[#14a800]'
                            : 'border-gray-100 bg-white text-[#5e6d55] hover:border-[#14a800]/30 hover:text-[#001e00]'
                            }`}
                    >
                        <Megaphone size={20} />
                        <span className="text-[10px] font-black uppercase tracking-tight">Advertiser</span>
                    </button>
                    <button
                        type="button"
                        onClick={() => setRole('admin')}
                        className={`flex flex-col items-center gap-2 p-4 rounded-xl border-2 transition-all ${role === 'admin'
                            ? 'border-[#14a800] bg-[#14a800]/5 text-[#14a800]'
                            : 'border-gray-100 bg-white text-[#5e6d55] hover:border-[#14a800]/30 hover:text-[#001e00]'
                            }`}
                    >
                        <ShieldCheck size={20} />
                        <span className="text-[10px] font-black uppercase tracking-tight">Admin</span>
                    </button>
                </div>
            </div>

            <div className="relative my-10">
                <div className="absolute inset-0 flex items-center">
                    <div className="w-full border-t border-gray-100"></div>
                </div>
                <div className="relative flex justify-center text-xs uppercase">
                    <span className="bg-white px-4 text-[#5e6d55] font-bold tracking-widest">
                        Or continue with
                    </span>
                </div>
            </div>

            <div className="grid grid-cols-3 gap-3">
                <button
                    type="button"
                    onClick={() => handleSocialAuth("oauth_facebook")}
                    disabled={loading}
                    className="flex h-12 items-center justify-center rounded-xl border border-gray-100 bg-white transition-all hover:bg-gray-50 active:scale-95 disabled:opacity-50 shadow-sm"
                >
                    <img src={FacebookIcon} alt="Facebook" className="h-6 w-6 object-contain" />
                </button>
                <button
                    type="button"
                    onClick={() => handleSocialAuth("oauth_tiktok")}
                    disabled={loading}
                    className="flex h-12 items-center justify-center rounded-xl border border-gray-100 bg-white transition-all hover:bg-gray-50 active:scale-95 disabled:opacity-50 shadow-sm"
                >
                    <img src={TiktokIcon} alt="TikTok" className="h-6 w-6 object-contain rounded" />
                </button>
                <button
                    type="button"
                    onClick={() => handleSocialAuth("oauth_google")}
                    disabled={loading}
                    className="flex h-12 items-center justify-center rounded-xl border border-gray-100 bg-white transition-all hover:bg-gray-50 active:scale-95 disabled:opacity-50 shadow-sm"
                >
                    <img src={GoogleIcon} alt="Google" className="h-6 w-6 object-contain" />
                </button>
            </div>

            <p className="mt-10 text-center text-sm font-medium text-[#5e6d55]">
                New to AACP?{" "}
                <Link
                    to="/auth/register"
                    className="font-bold text-[#14a800] hover:underline"
                >
                    Create account
                </Link>
            </p>
        </div>
    );
}
